apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adguard-ingress-operator.fullname" . }}-config
  labels:
    {{- include "adguard-ingress-operator.labels" . | nindent 4 }}
  {{- with .Values.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{ .Values.config.filePath }}: |
    instances:
      {{- toYaml .Values.config.instances | nindent 6 }}
